development:
  adapter: postgresql 
  encoding: unicode
  host: localhost
  port:	5432
  pool: 5
  username: app_user
  password: app_user
  database: app_test

production:
  adapter:  postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: app_user
  password: app_user
  database: postgres
